add_parcel:
  name: translation::services.add_parcel.name
  description: translation::services.add_parcel.description
  target:
    entity:
      domain: todo
      integration: boks
  fields:
    description:
      name: translation::services.add_parcel.fields.description.name
      description: translation::services.add_parcel.fields.description.description
      required: false
      selector:
        text:

add_pin_code:
  name: translation::services.add_pin_code.name
  description: translation::services.add_pin_code.description
  target:
    device:
      integration: boks
  fields:
    code:
      name: translation::services.add_pin_code.fields.code.name
      description: translation::services.add_pin_code.fields.code.description
      required: true
      selector:
        text:
    type:
      name: translation::services.add_pin_code.fields.type.name
      description: translation::services.add_pin_code.fields.type.description
      required: true
      selector:
        select:
          options:
            - single
            - multi
            - master
          mode: dropdown
    # valid_from et valid_until sont supprimés
    # index est déplacé ici si c'est pour master codes
    index:
      name: translation::services.add_pin_code.fields.index.name
      description: translation::services.add_pin_code.fields.index.description
      required: false
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box

delete_pin_code:
  name: translation::services.delete_pin_code.name
  description: translation::services.delete_pin_code.description
  target:
    device:
      integration: boks
  fields:
    identifier:
      name: translation::services.delete_pin_code.fields.identifier.name
      description: translation::services.delete_pin_code.fields.identifier.description
      required: true
      selector:
        text:
    type:
      name: translation::services.delete_pin_code.fields.type.name
      description: translation::services.delete_pin_code.fields.type.description
      required: true
      selector:
        select:
          options:
            - single
            - multi
            - master
          mode: dropdown

sync_logs:
  name: translation::services.sync_logs.name
  description: translation::services.sync_logs.description
  target:
    device:
      integration: boks